apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
    azure.workload.identity/use: "true"
  name: mypod
  namespace: default
spec:
  containers:
  - args:
    - bash
    #image: python:latest
    image: gcc:13.2.0
    name: mypod
    tty: true
  serviceAccountName: workload-identity-sa
 
